name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  #CI:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - 
  #      name: Checkout do código fonte
  #      uses: actions/checkout@v4.1.7

  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v3.2.0
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v6.2.0
  #       with:
  #         context: ./src
  #         push: true
  #         file: ./src/Review-Filmes.Web/Dockerfile
  #         tags: |
  #           diegoflavia/review-filmes:v${{ github.run_number }}
  #           diegoflavia/review-filmes:latest

  CD:
    runs-on: ubuntu-latest
    #needs: [CI]
    steps:
      - 
        name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Configuring AWS credentials"
          aws sts get-caller-identity

      - name: Kube update config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          aws eks update-kubeconfig --name EKSAula --region ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./k8s/deployment.yaml

      # -
      #   name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4.0.2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      # - 
      #   name: Deploy
      #   run: |
      #     aws eks update-kubeconfig --name EKSAula --region ${{ secrets.AWS_DEFAULT_REGION }}
      #     kubectl apply -f ./k8s/deployment.yaml

#export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
#export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
#export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}